### ISSUE TITLE
Create Online Interactive Demo

### ISSUE THREAD

**Issue by Fydar** [Fydar/RPGCore#15]
Create an interactive web-demo to allow users to interact with aspects of RPGCore.

Blazor can use the .NET Standard RPGCore logic to introduce users to the RPGCore APIs.

I can also utilise Roslyn in REPL mode (or scripting mode) to allow users to inject commands into the demo to further experiment with the RPGCore API.

Rendering an inventory and items inside the interactive demo would allow for interaction with them via the scripting API.

**Comment by MostHated** [comment]
Nice, I am definitely interested in checking this one out. : D 👍

**Comment by Fydar** [comment]
Closing this in favour of using Jupyter Notebook documentation; which allows for interactive code execution in a standardised format.
