### ISSUE TITLE
will you add skill system

### ISSUE THREAD

**Issue by li5414** [Fydar/RPGCore#8]
now you have item and buff,will you add skill system with node graph?

**Comment by Fydar** [comment]
Yeah, it's looking likely :)

The behaviour system has already been adapted to be used as apart of a skill system to apply effects to the player.

The current "behaviour node editor" wouldn't be appropriate for a skill **tree** editor; however I do have a work-in-progress skill tree editor that utilises Unity's UnityEngine.UI inside an editor window. This approach was adopted before Unity's UIElements; which will require investigation. Using Unity's UI right inside the editor allows for seeing what the skill tree will look like in realtime.

As it stands; the skill tree editor is too single-game-specific; and in it's current form won't be very useful. Until the rewrite is complete I don't know what new features I will be addressing first; but this has got to be at the top of the list.
